### ISSUE TITLE
gulp generates typescript errors

### ISSUE THREAD

**Issue by BurtHarris** [TypeForce/tsdoc#7]
Running gulp on the current repository I get two TypeScript errors.

- I simply don't understand the one at **src/index.ts(2,55)**.   

- **src\documenter.ts(58,42)** looks a genuine mistake, the return type of `renderer.render()` is void, but you are passing it as an argument.

It might be a good idea to use a CI service like Travis.CI or appveyor and start using a pull-request model for commits to master.   I've got a few other suggestions, but want to get this fixed before I move on.

```
C:\code\tsdoc>gulp
[11:08:24] Using gulpfile C:\code\tsdoc\gulpfile.js
[11:08:24] Starting 'compile'...
src\index.ts(2,55): error TS2307: Cannot find module 'tsdoc'.
[11:08:25] TypeScript: 1 semantic error
[11:08:25] TypeScript: emit succeeded (with errors)
src\documenter.ts(58,42): error TS2345: Argument of type 'void' is not assignable to parameter of type 'string'.
[11:08:28] TypeScript: 1 semantic error
[11:08:28] TypeScript: emit succeeded (with errors)
[11:08:28] Finished 'compile' after 3.7 s
[11:08:28] Starting 'default'...
[11:08:28] Finished 'default' after 64 μs

C:\code\tsdoc>npm --versions
{ tsdoc: '0.0.1',
  npm: '5.1.0',
  ares: '1.10.1-DEV',
  cldr: '31.0.1',
  http_parser: '2.7.0',
  icu: '59.1',
  modules: '57',
  node: '8.1.3',
  openssl: '1.0.2l',
  tz: '2017b',
  unicode: '9.0',
  uv: '1.12.0',
  v8: '5.8.283.41',
  zlib: '1.2.11' }
```

**Comment by samvv** [comment]
Hmm indeed it might be better to use a pull-request system. Besides, I have a lot of breaking changes locally which I want to merge as soon as possible so that we can work independently. As for the first error: it seems to be an issue with [gulp-typescript](https://www.npmjs.com/package/gulp-typescript) ... kind of: I needed to provide a `cwd` with each sub-project which causes part of the path to disappear. The actual error lies in `plugins/example/src/index.ts`.

**Comment by samvv** [comment]
Another issue is again the linking. Sorry about that. `plugins/example` needs to know about `tsdoc` so it can import core types and interfaces properly.

**Comment by BurtHarris** [comment]
Ahh, I've dealt with something like that before.   Its a bit tricky, you want a multi-package repository.   Lerna has this as a goal, but 2.0-rc has a nasty incompatibility with npm@5, so I can't recommend it right now.    I'm dealing with a similar problem in the antlr4ts project, I'll tackle that one if you can fix the 
src\documenter.ts(58,42) one.

**Comment by samvv** [comment]
All right! And cool, didn't know about Lerna. Looks very interesting, and highly similar to an idea I once had.

**Comment by samvv** [comment]
They should be fixed with my latest pull request.

**Comment by BurtHarris** [comment]
I think this is fixed, or will be with my pending PR #24
